version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - n:triage
  - t:cleanup
  ignore:
  - dependency-name: cap-std
    versions:
    - 0.12.0
    - 0.13.0
    - 0.13.3
    - 0.13.6
    - 0.13.7
  - dependency-name: syn
    versions:
    - 1.0.60
    - 1.0.61
    - 1.0.62
    - 1.0.63
    - 1.0.64
    - 1.0.67
  - dependency-name: pin-project
    versions:
    - 1.0.5
    - 1.0.6
  - dependency-name: serde
    versions:
    - 1.0.121
    - 1.0.124
    - 1.0.125
  - dependency-name: nom
    versions:
    - 6.1.0
    - 6.1.2
  - dependency-name: assert_fs
    versions:
    - 1.0.1
  - dependency-name: rand
    versions:
    - 0.8.3
  - dependency-name: criterion
    versions:
    - 0.3.4
  - dependency-name: quickcheck
    versions:
    - 1.0.3
  - dependency-name: futures-test
    versions:
    - 0.3.12
