language: nix
nix: 2.1

# TODO: (C) Add coverage reporting

matrix:
  include:
    - name: cargo fmt
      script: nix-shell --run 'cargo fmt --all -- --check'
    - name: cargo build
      script: nix-shell --run 'cargo build --all --all-features'
    - name: cargo test
      script: nix-shell --run 'cargo test --all --all-features'
    - name: cargo doc
      script: nix-shell --run 'cargo doc --all --all-features && mv target/doc doc/dev-doc'
    - name: mdbook build
      script: nix-shell --run 'mdbook build book && mv doc/book doc/'
    - name: mdbook test
      script: nix-shell --run 'mdbook test book'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: doc
  on:
    branch: master
