language: rust
cache: cargo

sudo: required
os: [ linux ]

rust:
  - 1.25.0
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: stable
      env: TARPAULIN=1
    - rust: nightly
      env: CHECK_FORMAT=1

before_script: |
  export PATH="$HOME/.cargo/bin:$PATH"
  if [ -n "$TARPAULIN" ]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  elif [ -n "$CHECK_FORMAT" ]; then
    rustup component add rustfmt-preview --toolchain nightly
  fi

# TODO: auto-build doc and push it to github pages (both cargo doc and mdBook?)
script: |
  if [ -n "$TARPAULIN" ]; then
    cargo tarpaulin --out Xml
  elif [ -n "$CHECK_FORMAT" ]; then
    rustfmt --version
    cargo +nightly fmt --all -- --write-mode=diff
  else
    cargo build --all --all-features
    cargo test --all --all-features
  fi

after_success: |
  if [ -n "$TARPAULIN" ]; then
    bash <(curl -s https://codecov.io/bash)
  fi
