[workspace]
members = [ "smtp-message", "smtp-message/fuzz",
            "smtp-server", "smtp-server/fuzz",
            "smtp-queue", "smtp-queue-fs" ]

[profile.release]
lto = true

[profile.bench]
lto = true
