[package]
name = "smtp-queue"
version = "0.1.0"
authors = ["Léo Gaspard <leo@gaspard.io>"]
license = "MIT"
categories = ["email", "network-programming"]
keywords = ["queue", "smtp", "email"]
description = "Queue for SMTP messages using smol"
edition = "2018"

[dependencies]
async-trait = "0.1.30"
bytes = "0.5.4"
chrono = "0.4.11"
futures = "0.3.4"
smtp-message = { path = "../smtp-message" }
smol = "0.1.4"
