[book]
authors = ["Léo Gaspard"]
language = "en"
multilingual = false
src = "src"
title = "kannader"

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/Ekleog/kannader"
